test

diff --git a/.github/workflows/create-branch.yml b/.github/workflows/create-branch.yml
--- a/.github/workflows/create-branch.yml
+++ b/.github/workflows/create-branch.yml
@@ -12,7 +12,7 @@ on:
 
 
 jobs:
-  create-branche-and-pr:
+  create-branche:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -20,6 +20,22 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           git-ref: ${{ inputs.git-tag }}
+      - name: Append SNAPSHOT to the version
+        run: |
+          FILE="build.txt"
+          # Get the version from build.txt
+          VERSION=$(awk -F'=' '/^version=/ {print $2}' "$FILE")
+          echo "Current version is $VERSION"
+          #if version is empty, exit
+          if [ -z "$VERSION" ]; then
+          echo "Version not found in $FILE"
+          exit 1
+          fi
+          #Add -SNAPSHOT to the version
+          NEW_VERSION="${VERSION}-SNAPSHOT"
+          echo "New version is $NEW_VERSION"
+          # Set the new version in build.txt
+          sed -i.bak "s/^version=.*/version=${NEW_VERSION}/" $FILE
       - name: Create Branch
         shell: bash
         run: |
